name: Build ARIA Android

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar proyecto
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Configurar Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.9'

      - name: Compilar ARIA
        run: gradle :app:assembleDebug --stacktrace

      - name: Guardar APK
        uses: actions/upload-artifact@v4
        with:
          name: ARIA-Mobile-Alpha-0.1
          path: app/build/outputs/apk/debug/app-debug.apk
